Rela Web/rela project/Controllers/CheckSimilarityController.cs
using Newtonsoft.Json;
using Rela_project.Models;
using Rela_project.Models.CheckSimilarity;
using Rela_project.Models.Home;
using Rela_project.Models.LogIn;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Rela_project.Controllers
{
    public class CheckSimilarityController : Controller
    {
        [HttpGet]
        [RequireHttps]
        public async Task<ActionResult> CheckResultView() {
            await saveLog();
            if (Session.Count == 0)
            {
                TempData["LogInError"] = "Session has ended. Please log in again.";
                return RedirectToAction("Index", "LogIn");
            }
            ViewBag.ChekcSimilarityError = TempData["ChekcSimilarityError"];
            return View();
        }

        [HttpPost]
        [RequireHttps]
        public async Task<ActionResult> DisplayResults3View(Similarity3Persons similarity3Persons)
        {
            string SECRETKEY = ConfigurationManager.AppSettings["captchaSecret"];
            string userResponse = similarity3Persons.gRecaptchaResponse;
            var webClient = new WebClient();
            string verification = webClient.DownloadString(ConfigurationManager.AppSettings["captchaLink"] + "secret=" + SECRETKEY + "&response=" + userResponse);
            var verificationJson = JsonConvert.DeserializeObject<CaptchaResponse>(verification);
            bool rezultati = verificationJson.success;
            var httpClient = new HttpClient();
            var jsonCaptchaLogs = new Logs { action = verificationJson.action, challenge_ts = verificationJson.challenge_ts, score = verificationJson.score, time_accessed = DateTime.Now, ip = Request.UserHostAddress, hostname = Request.UserHostName, success = verificationJson.success, url = Request.Url.ToString() };
            var captchaContent = new StringContent(JsonConvert.SerializeObject(jsonCaptchaLogs), Encoding.ASCII, "application/json");
            await httpClient.PostAsync(ConfigurationManager.AppSettings["url"] + "api/logs/saveRecaptchaLogs", captchaContent);

            if (Session.Count == 0)
            {
                TempData["LogInError"] = "Session has ended. Please log in again.";
                return RedirectToAction("Index", "LogIn");
            }

            try
            {
                User user = (User)Session["userSession"];
                byte[] motherByte = new byte[similarity3Persons.mother.ContentLength];
                await similarity3Persons.mother.InputStream.ReadAsync(motherByte, 0, similarity3Persons.mother.ContentLength);
                string motherToBase64 = Convert.ToBase64String(motherByte, 0, motherByte.Length);

                byte[] fatherByte = new byte[similarity3Persons.father.ContentLength];
                await similarity3Persons.father.InputStream.ReadAsync(fatherByte, 0, similarity3Persons.father.ContentLength);
                string fatherToBase64 = Convert.ToBase64String(fatherByte, 0, fatherByte.Length);

                byte[] childrenByte = new byte[similarity3Persons.children.ContentLength];
                await similarity3Persons.children.InputStream.ReadAsync(childrenByte, 0, similarity3Persons.children.ContentLength);
                string childrenToBase64 = Convert.ToBase64String(childrenByte, 0, childrenByte.Length);

                if (Session["checkSimilarity3"] != null)
                {
                    var SessionData = (DisplayResultsModel)Session["checkSimilarity3"];
                    if (SessionData.father == fatherToBase64 && SessionData.mother == motherToBase64 && SessionData.children == childrenToBase64)
                        return View(SessionData);
                }

                var compareFaces = new CompareFaces { userId = user.userId, fatherPhoto = fatherToBase64, motherPhoto = motherToBase64, childrenPhoto = childrenToBase64 };

                var content = new StringContent(JsonConvert.SerializeObject(compareFaces), Encoding.UTF8, "application/json");

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Session["Access_Token"].ToString());

                var responseApi = await httpClient.PostAsync(ConfigurationManager.AppSettings["url"] + "api/FaceRecognition/CheckSimilarityResults", content);
                var result = await responseApi.Content.ReadAsStringAsync();

                if (!responseApi.IsSuccessStatusCode)
                {
                    var mesage = JsonConvert.DeserializeObject<Error>(result);
                    TempData["errorCheckSimilarity"] = mesage.Message;
                    return RedirectToAction("CheckResultView");
                }

                var checkSimilarity = JsonConvert.DeserializeObject<CheckSimilarity>(result);
                var displayResultsModel = new DisplayResultsModel { checkSimilarity = checkSimilarity, father = fatherToBase64, mother = motherToBase64, children = childrenToBase64 };
                Session["checkSimilarity3"] = displayResultsModel;
                return View(displayResultsModel);
            }
            catch (Exception ex)
            {
                TempData["errorCheckSimilarity"] = ex.ToString();
                return RedirectToAction("CheckResultView");
            }
        }

        [HttpPost]
        [RequireHttps]
        public async Task<ActionResult> DisplayResultsTogetherView(HttpPostedFileBase familyTogether) {
            await saveLog();
            if (Session.Count == 0)
            {
                TempData["LogInError"] = "Session has ended. Please log in again.";
                return RedirectToAction("Index", "LogIn");
            }
            var httpClient = new HttpClient();
                try
                {
                    User user = (User)Session["userSession"];
                    byte[] familyTogetherByte = new byte[familyTogether.ContentLength];
                    await familyTogether.InputStream.ReadAsync(familyTogetherByte, 0, familyTogether.ContentLength);
                    string familyToBase64 = Convert.ToBase64String(familyTogetherByte, 0, familyTogetherByte.Length);

                if (Session["FamilyCheckResult"] != null) {
                    var SessionData = (DisplayResultModelFamily)Session["FamilyCheckResult"];
                    if (SessionData.familyPhoto == familyToBase64)
                        return View(SessionData);
                }

                    var compareFamily = new CompareFacesFamily { userId = user.userId, familyPhoto = familyToBase64 };

                    var content = new StringContent(JsonConvert.SerializeObject(compareFamily), Encoding.UTF8, "application/json");

                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Session["Access_Token"].ToString());

                    var responseApi = await httpClient.PostAsync(ConfigurationManager.AppSettings["url"] + "api/FaceRecognition/FamilyCheck", content);
                    var result = await responseApi.Content.ReadAsStringAsync();

                var errorMessage = JsonConvert.DeserializeObject<Error>(result);
                if(errorMessage.Message != null)
                {
                    TempData["ChekcSimilarityError"] = errorMessage.Message;
                    return RedirectToAction("CheckResultView");
                }
                    

                if (responseApi.StatusCode == (HttpStatusCode)429) {
                    TempData["ChekcSimilarityError"] = "429";
                    return RedirectToAction("CheckResultView");
                }


                    var checkSimilarityTogether = JsonConvert.DeserializeObject<CheckSimilarityTogether>(result);

                    Session["FamilyCheckResult"] = new DisplayResultModelFamily {checkSimilarityTogether = checkSimilarityTogether, familyPhoto = familyToBase64 };

                    return View(new DisplayResultModelFamily { checkSimilarityTogether = checkSimilarityTogether, familyPhoto = familyToBase64 });
                }
                catch (Exception ex)
                {
                    return RedirectToAction("CheckResultView");
                }
        }

        [HttpGet]
        [RequireHttps]
        public async Task<ActionResult> ImagesProcesedHistory() {
            await saveLog();
            if (Session.Count == 0)
            {
                TempData["LogInError"] = "Session has ended. Please log in again.";
                return RedirectToAction("Index", "LogIn");
            }

            User user = (User)Session["userSession"];

            var httpClient = new HttpClient();
            var content = new StringContent(JsonConvert.SerializeObject(new { userId = user.userId}),Encoding.UTF8, "application/json");
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Session["Access_Token"].ToString());
            var response = await httpClient.PostAsync(ConfigurationManager.AppSettings["url"] + "api/History/GetImages", content);
            var result = await response.Content.ReadAsStringAsync();
            var listOfImages = JsonConvert.DeserializeObject<List<HistoryCheckSimilarity>>(result);
            return View(listOfImages);
        }

        [HttpPost]
        [RequireHttps]
        public async Task<ActionResult> findFatherMotherChildren(HttpPostedFileBase familyTogether)
        {
            await saveLog();
            if (Session.Count == 0)
            {
                TempData["LogInError"] = "Session has ended. Please log in again.";
                return RedirectToAction("Index", "LogIn");
            }
            var httpClient = new HttpClient();
            try
            {

Rela Web/rela project/Views/CheckSimilarity/CheckResultView.cshtml
@{
    ViewBag.Title = "Check Similarity View";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var checkErorrResult = ViewBag.ChekcSimilarityError;
}

<link href="~/Content/toastr.min.css" rel="stylesheet" />
<script src="~/Scripts/toastr.min.js"></script>

<div class="alert alert-dismissible alert-danger d-none" id="alertToManyRequest">
    <button class="close" type="button" data-dismiss="alert">&times;</button>
    <h4 class="alert-heading">To many request</h4>
    <p class="mb-0">Dear user you have exceeded the maximum number of request that you can make to this site. To protect this site from potentional attack, we have blocked this service right now. You can try again after <b>5 minutes</b> and it will work.</p>
</div>

<div class="alert alert-dismissible alert-danger d-none" id="alertNumberFaces">
    <button class="close" type="button" data-dismiss="alert">&times;</button>
    <h4 class="alert-heading"> Image not correct </h4>
    <p class="mb-0"> Dear user, in order to process your image correctly we need image with 3 or more faces. Our system has detected that there are @checkErorrResult faces.</p>
</div>

<div class="alert alert-dismissible alert-danger d-none" id="alertFaceError">
    <button class="close" type="button" data-dismiss="alert">&times;</button>
    <h4 class="alert-heading"> Images not correct </h4>
    <p class="mb-0"> @checkErorrResult </p>
</div>



<div id="accordion">
    <div class="card">
        <div class="card-header">
            <a class="card-link" data-toggle="collapse" href="#collapseOne">
                Check your similarity with your parents with different photo
            </a>
        </div>
        <div id="collapseOne" class="collapse show" data-parent="#accordion">
            <div class="card-body">
                @using (Html.BeginForm("DisplayResults3View", "CheckSimilarity", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                {
                    <script>
                        grecaptcha.ready(function () {
                            grecaptcha.execute('6LePo4YUAAAAAJF4KNSNsBxshWHSmJLwAVQjIoOX', { action: 'Index' }).then(function (token) {
                                $("#g-recaptcha-response").val(token);
                            });
                        });
                    </script>
                    <input type="hidden" id="g-recaptcha-response" name="gRecaptchaResponse">
                    <div class="row" id="selectUsersDifferent">
                        <div class=" col-sm-4 mb-3">
                            <div class="card w-75 d-block m-auto">
                                <div class="card-header">
                                    <h5 style="text-align:center">Father</h5>
                                </div>
                                <div class="card-body">
                                    <img src="~/Images/Father.png" style="width:80%" class="rounded-circle d-block m-auto" id="fatherImage" />
                                    <div class="custom-file">
                                        <input type="file" id="father" name="father" class="custom-file-input" onchange="displayImportedImage(this,'fatherImage','father');" />
                                        <label class="custom-file-label" for="father">Choose file</label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-4 mb-3">
                            <div class="card w-75 d-block m-auto">
                                <div class="card-header">
                                    <h5 style="text-align:center">Mother</h5>
                                </div>
                                <div class="card-body">
                                    <img src="~/Images/407475-mother-icon-illustration.jpg" style="width:80%" class="rounded-circle d-block m-auto" id="motherImage" />
                                    <div class="custom-file">
                                        <input type="file" id="mother" name="mother" required class="custom-file-input" onchange="displayImportedImage(this, 'motherImage', 'mother');" />
                                        <label class="custom-file-label" for="mother">Choose file</label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-4 mb-3">
                            <div class="card w-75 d-block m-auto">
                                <div class="card-header">
                                    <h5 style="text-align:center">Children</h5>
                                </div>
                                <div class="card-body">
                                    <img src="~/Images/child.png" style="width:80%" class="rounded-circle d-block m-auto" id="childrenImage" />
                                    <div class="custom-file">
                                        <input type="file" id="children" name="children" required class="custom-file-input" onchange="displayImportedImage(this,'childrenImage','children')" />
                                        <label class="custom-file-label" for="childrenFile">Choose file</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="submit" value="Compare" class="btn btn-outline-info d-block" style="margin:auto;margin-top:30px; padding:5px 10px;" id="btnFamily3" />
                }
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <a class="card-link" data-toggle="collapse" href="#collapseTwo">
                Check your similarity with your parents in one photo
            </a>
        </div>
        <div id="collapseTwo" class="collapse" data-parent="#accordion">
            <div class="card-body">
                @using (Html.BeginForm("findFatherMotherChildren", "CheckSimilarity", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                {
                    <script>
                        grecaptcha.ready(function () {
                            grecaptcha.execute('6LePo4YUAAAAAJF4KNSNsBxshWHSmJLwAVQjIoOX', { action: 'Index' }).then(function (token) {
                                $("#g-recaptcha-response").val(token);
                            });
                        });
                    </script>
                    <input type="hidden" id="g-recaptcha-response" name="gRecaptchaResponse">
                    <div class="text-danger mb-2 ml-2">
                        Please choose image with 3 faces.
                    </div>
                    <div class="row">
                        <div class="col-md-9 mb-3">
                            <div class="card d-block m-auto" style="width:50%">
                                <div class="card-header">
                                    <h5 style="text-align:center;color:black"> Togethere photo </h5>
                                </div>
                                <div class="card-body">
                                    <img src="~/Images/37-512.png" style="width:100%; z-index: 0" id="familyImage" />
                                    <div class="custom-file">
                                        <input type="file" id="familyTogether" name="familyTogether" required class="custom-file-input" onchange="displayImportedImage(this, 'familyImage', 'familyTogether');" />
                                        <label class="custom-file-label" for="familyTogether">Choose file</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3 d-block m-auto">
                            <input type="submit" value="Compare" class="btn btn-outline-info d-block m-auto" id="bntFamilyCompare" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>


<div class="modal" id="modalLogIn">
    <div class="modal-dialog-centered">
        <div class="modal-body d-block m-auto">
            <img src="~/Images/loading.gif" class="d-block m-auto p-4" />
        </div>
    </div>
</div>


<script>
    if ("@checkErorrResult" == "429") {
        $("#alertToManyRequest").removeClass("d-none");
        $("#alertToManyRequest").addClass("d-block");
    } else if (!isNaN(@checkErorrResult)) {
        $("#alertNumberFaces").removeClass("d-none");
        $("#alertNumberFaces").addClass("d-block");
    } else if ("@checkErorrResult" != "") {
        $("#alertFaceError").removeClass("d-none");
        $("#alertFaceError").addClass("d-block");
    }

    $("#bntFamilyCompare").click(function () {
        $("#modalLogIn").modal("toggle");
    });

    $("#btnFamily3").click(function () {
        $("#modalLogIn").modal("toggle");
    });

    function displayImportedImage(image, imageId, fileInputId) {
        if (FileReader) {
            var reader = new FileReader();
            reader.readAsDataURL(image.files[0]);
            reader.onload = function (e) {
                var image = new Image();
                image.src = e.target.result;
                image.onload = function () {
                    $("#" + fileInputId).append('');
                    $("#" + imageId).attr("src", image.src);
                };
            }
        }
    }
</script>

Rela Web/rela project/Views/CheckSimilarity/ImagesProcesedHistory.cshtml
@model IEnumerable<Rela_project.Models.CheckSimilarity.HistoryCheckSimilarity>
@{
    ViewBag.Title = "Images Procesed";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var imagesHistory = Model.ToList();
}
<style>
    .carousel-inner img {
        width: 100%;
        height: 100%;
        max-width:500px;
        max-height:500px;
    }
</style>

<p style="font-size:1.6em">
    History of procesed images
</p>

@{
    if (imagesHistory.Count > 0)
    {
<div class="d-block m-auto" style="width:500px; height:500px;">
    <div id="historyImagesProcesed" class="carousel slide" data-ride="carousel">
        <ul class="carousel-indicators">
            @{
                foreach (var image in imagesHistory)
                {
                    if (imagesHistory.IndexOf(image) == 0)
                    {
                        <li data-target="#historyImagesProcesed" data-slide-to="@imagesHistory.IndexOf(image)" class="active"></li>
                    }

                    else
                    {
                        <li data-target="#historyImagesProcesed" data-slide-to="@imagesHistory.IndexOf(image)"></li>
                    }
                }
            }
        </ul>

        <div class="carousel-inner">
            @{
                foreach (var image in imagesHistory)
                {
                    if (imagesHistory.IndexOf(image) == 0)
                    {
                        <div class="carousel-item active">
                            <img src="data:Image/png;base64,@image.image">
                        </div>
                    }
                    else
                    {
                        <div class="carousel-item">
                            <img src="data:Image/png;base64,@image.image">
                        </div>
                    }
                }

            }
        </div>

        <a class="carousel-control-prev" href="#historyImagesProcesed" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#historyImagesProcesed" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</div>
    }
    else
    {
        <div class="alert alert-dismissible alert-info">
            <button class="close" type="button" data-dismiss="alert">&times;</button>
            <h4 class="alert-heading">No photo</h4>
            <p class="mb-0"> Dear user you do not have any image procesed in our site. If you want to make history and enjoy this project <b><a class="alert-link" href="/Home/Main">click here</a></b>.</p>
        </div>
    }
}

Rela Web/rela project/Views/CheckSimilarity/findFatherMotherChildren.cshtml
@model Rela_project.Models.CheckSimilarity.DisplayResultModelFamily

@{
    ViewBag.Title = "Display Results";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var customer = Model;
}
<link href="~/DataTable/datatables.min.css" rel="stylesheet" />
<script src="~/DataTable/datatables.min.js"></script>
<script src="~/DataTable/pdfmake-0.1.36/pdfmake.min.js"></script>
<script>
    var usersImageDimension = [];

    function drawRentagleToUser(topOriginal, leftOriginal, widthRentagleOriginal, heightRentagleOriginal, imageId, position) {
        var rentagleOverPhoto = document.getElementById("drawRentagle");
        var context = rentagleOverPhoto.getContext("2d");
        context.strokeStyle = "#FFFF00"
        context.lineWidth = 5;
        var image = document.getElementById(imageId);
        var originalWidth = parseFloat(image.naturalWidth);
        var originalHeight = parseFloat(image.naturalHeight);
        var shrinkedWidth = parseFloat(image.clientWidth);
        var shrinkedHeight = parseFloat(image.clientHeight);
        var koeficientiZvoglimitGjatesor = originalWidth / shrinkedWidth;
        var koeficinetZvoglimitLartesise = originalHeight / shrinkedHeight;
        var rentagleOfImageWidth = parseFloat(widthRentagleOriginal) / koeficientiZvoglimitGjatesor;
        var rentagleOfImageHeight = parseFloat(heightRentagleOriginal) / koeficinetZvoglimitLartesise;
        var topOfImage = parseFloat(topOriginal) / koeficientiZvoglimitGjatesor - 56;
        var leftOfImage = parseFloat(leftOriginal) / koeficinetZvoglimitLartesise + 16;

        context.strokeRect(leftOfImage, topOfImage, rentagleOfImageWidth, rentagleOfImageHeight);
        context.font = "20px Arial";
        context.fillStyle = "yellow";
        context.fillText(position, leftOfImage + 10, topOfImage + 20);
        //   context.font = "20px Arial";
        //todo
    }
</script>
<p style="text-align:center; font-size:1.6em;margin-bottom:40px">
    Family display check results
</p>

@using (Ajax.BeginForm("updateDiv", "CheckSimilarity", new AjaxOptions
{
    UpdateTargetId = "updateTargetDiv",
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace
     
}))
{
    <div class="row">
        <div class="col-md-7 mb-3">
            <div id="canvasRemove">
                <img src="data:Image/png;base64,@customer.familyPhoto" style="width:90%; z-index: -1; max-width:400px" id="familyImageReal" />
                <canvas id="drawRentagle" style="position:absolute; top:55px; left:0px; z-index:1;"></canvas>
            </div>
        </div>

        <div class="col-md-5">
            <div class="text-body">
                Dear user, our system has defined @customer.checkSimilarityTogether.cognitiveMicrosoft.Count faces. Based on our system we have defined father, mother and children in this order:

                <div class="form-group">
                    <label for="father"> Father position </label>
                    <select class="form-control" id="father" name="father"></select>
                </div>

                <div class="form-group">
                    <label for="mother">Mother position </label>
                    <select class="form-control" id="mother" name="mother"></select>
                </div>

                <div class="form-group">
                    <label for="children">Children position</label>
                    <select class="form-control" id="children" name="children"></select>
                </div>
            </div>

            <div class="text-body text-justify">
                <p> If our system has detected faces correctly just click button Check similarity. If faces are not detected correctly jus select them in dropdown lists and click the same button.</p>
            </div>

        </div>

        <button type="submit" class="btn btn-outline-primary d-block m-auto"> Check similarity </button>
    </div>
}
<div id="updateTargetDiv">

</div>

@{
    int k = 1;
    foreach (var user in customer.checkSimilarityTogether.cognitiveMicrosoft)
    {
        <script>
            $("#father").append('<option value="@user.faceId">' + @k + '</option>')
            $("#mother").append('<option value="@user.faceId">' + @k + '</option>')
            $("#children").append('<option value="@user.faceId">' + @k + '</option>')
        </script>
        k++;
    }
}
<script>
    function convertToPercentage(value) {
        var valueFromController = parseFloat(value) * 100;
        var exactValue = Math.round(valueFromController);
        document.write(exactValue);
        return exactValue;
    }
        $("#father").val("@customer.checkSimilarityTogether.cognitiveMicrosoft[customer.checkSimilarityTogether.fatherPositon].faceId");
        $("#mother").val("@customer.checkSimilarityTogether.cognitiveMicrosoft[customer.checkSimilarityTogether.motherPosition].faceId");
        $("#children").val("@customer.checkSimilarityTogether.cognitiveMicrosoft[customer.checkSimilarityTogether.childrenPosition].faceId");

    function resizeRentagle() {
        for (i = 0; i < usersImageDimension.length; i++) {
            if (i % 4 == 0) {
                drawRentagleToUser(usersImageDimension[i], usersImageDimension[i + 1], usersImageDimension[i + 2], usersImageDimension[i + 3], "familyImageReal");
            }
        }
    }

    var imageWidth = document.getElementById("familyImageReal").clientWidth;
    var imageHeight = document.getElementById("familyImageReal").clientHeight;
    $("#drawRentagle").attr("width", imageWidth);
    $("#drawRentagle").attr("height", imageHeight);

    $(window).resize(function () {
        $("#drawRentagle").remove();
        var width = document.getElementById("familyImageReal").clientWidth;
        var height = document.getElementById("familyImageReal").clientHeight;
        $("#canvasRemove").append('<canvas id="drawRentagle" height=' + height + ' width=' + width + ' style="position:absolute; top:55px; left:0px; z-index:1;"></canvas>');
        resizeRentagle();
        });
</script>
@{
    for (int i = 0; i < customer.checkSimilarityTogether.cognitiveMicrosoft.Count; i++)
    {
        <script>
        usersImageDimension.push(@customer.checkSimilarityTogether.cognitiveMicrosoft[i].faceRectangle.top);
        usersImageDimension.push(@customer.checkSimilarityTogether.cognitiveMicrosoft[i].faceRectangle.left);
        usersImageDimension.push(@customer.checkSimilarityTogether.cognitiveMicrosoft[i].faceRectangle.width);
        usersImageDimension.push(@customer.checkSimilarityTogether.cognitiveMicrosoft[i].faceRectangle.height);
        drawRentagleToUser("@customer.checkSimilarityTogether.cognitiveMicrosoft[i].faceRectangle.top", "@customer.checkSimilarityTogether.cognitiveMicrosoft[i].faceRectangle.left", "@customer.checkSimilarityTogether.cognitiveMicrosoft[i].faceRectangle.width", "@customer.checkSimilarityTogether.cognitiveMicrosoft[i].faceRectangle.height", "familyImageReal", "@(i+1)");
        </script>
    }
}